version: '3'
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh:z
    working_dir: /workspace
    network_mode: host
    environment:
      - TZ=Europe/Madrid
    command: [ "tail", "-f", "/dev/null" ]